version: '3.8'

services:
  redis:
    image: redis:7.2.4 #redis:7.2.4-alpine
    container_name: cache
    expose:
      - 6379
    ports:
      - '6379:6379'
    healthcheck:
      test: redis-cli ping
      interval: 3s
      timeout: 5s
      retries: 5

  redis-insight:
    image: redis/redisinsight:2.48.0
    ports:
      - '5540:5540'
    links:
      - redis
    # volumes:                            # Uncomment this to persist data
    #   - redis-insight:/data

  app:
    build: ./
    entrypoint: []
    links:
      - redis
    ports:
      - 9000:9000
    environment:
      - REDIS_URL=redis://cache
      - NODE_ENV=production
      - PORT=9000
      - JWT_SECRET=/run/secrets/JWT_SECRET
    secrets:
      - JWT_SECRET
    command: /bin/sh -c 'bun start'

secrets:
  JWT_SECRET:
    external: true
